# Generated by Django 2.2 on 2019-04-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180708_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(default='N', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductCondition'),
        ),
    ]
